# Generated by Django 6.1.1 on 2026-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(help_text='The station identifier (allows temporary CSV duplicates before deduplication)')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='2-letter US state code', max_length=2)),
                ('rack_id', models.IntegerField(help_text='The supply terminal identifier')),
                ('price', models.FloatField(help_text='Retail fuel price ($/gallon)')),
                ('latitude', models.FloatField(blank=True, help_text='GPS Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='GPS Longitude coordinate', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_stat_lat_lon_idx')],
            },
        ),
    ]
